### ISSUE TITLE
Stage: Borough President hearings information not displaying.

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#1036]
Project Name Happy Halloween
Email: gchandrausdob@gmail.com

Actual Result: Borough President hearings information not displaying.

Expected Result: Borough President hearings information should display in LUP Borough President Hearings Section.

![image](https://user-images.githubusercontent.com/57265341/70066692-198d9c00-15bb-11ea-80f1-f3e31572d204.png)

**Comment by allthesignals** [comment]
https://zap-staging.planninglabs.nyc/my-projects/upcoming?email=gchandrausdob%40gmail.com

**Comment by allthesignals** [comment]
The computed property dispositionsByRole isn't find anything for this... will look

**Comment by allthesignals** [comment]
![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/637f8f76-eb37-44bb-99d8-9299a061892e)

The dcpRepresenting columns are coming back null, so the computed property can't sort which dispositions go to whom.

**Comment by hannahkates** [comment]
This header shouldn't be showing up at all. Both dispositions for the user are Draft, not Saved, meaning they don't have any hearing data. Also neither of the dispositions have LUP or General Public visibility, so they shouldn't be coming back in the response.

![image](https://user-images.githubusercontent.com/13967925/70072403-ec45eb80-15c4-11ea-9ba5-5e3743725612.png)

**Comment by allthesignals** [comment]
Okay. Hmmm... so is this a query issue? Anything I can do to help?

**Comment by hannahkates** [comment]
dcp_representing is returned when running the SQL query on the database but it's not included for all of the dispositions in the final API response.

**Comment by allthesignals** [comment]
@hannahkates how'd you check this?

I'm running this code:
```
      const records = await getConnection().query(SQL);
      console.log(records[0].dispositions.map(dispo => dispo.dcp_representing));
```

After the raw query runs.

It's only showing:
```
[ 'Community Board' ]
```

**Comment by allthesignals** [comment]
Somehow it's linking 6 dispositions to this record

**Comment by allthesignals** [comment]
It's linking the 5 _project_ dispositions to the assignment _after_ the query response.

**Comment by allthesignals** [comment]
@hannahkates this assignment is only for BP, but there are no BP dispositions returned from the query.

**Comment by hannahkates** [comment]
This was a problem with the naming of an attribute in the SQL query. We've pushed a fix. QA please check.

**Comment by ksinghprod** [comment]
This is still an issue, especially when I assign the same LUP (Komalpreet singh) different roles (BP and CB) the BP hearing option does not show up

![image](https://user-images.githubusercontent.com/57362229/70088610-908b5a80-15e4-11ea-959c-88cdc7de2366.png)

**Comment by hannahkates** [comment]
Fixed! We've got a button now! QA team, please retest.

![image](https://user-images.githubusercontent.com/13967925/70095460-c3d4e600-15f2-11ea-88e5-e9f26c03fcaf.png)

**Comment by ksinghprod** [comment]
This issue is now fixed

![image](https://user-images.githubusercontent.com/57362229/70155787-e57cae80-1680-11ea-9d4a-fa092c039eae.png)
