### ISSUE TITLE
On the Public hearing record, The action name is not displaying 

### ISSUE THREAD

**Issue by ksinghprod** [NYCPlanning/labs-zap-search#933]
Browser: Chrome
Project name: 130-24 South Conduit Ave Self Storage 

Expected Result On the Public hearing record, the LUP user should be able to see the name of the action for which he/she is submitting a public hearing for.

Actual Result: On the Public hearing record, The action name is not displaying 

![image](https://user-images.githubusercontent.com/57362229/68891731-75b57c80-06ef-11ea-9f1e-6971ab6a3a1a.png)

**Comment by trbmcginnis** [comment]
Closing and combining into #976

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

**Comment by ksinghprod** [comment]
This is now fixed 

![image](https://user-images.githubusercontent.com/57362229/69578392-66abb580-0f9e-11ea-9917-4fcb65a89d0d.png)

**Comment by ksinghprod** [comment]
This issue is back 

![image](https://user-images.githubusercontent.com/57362229/70156678-5375a580-1682-11ea-8824-52cf6677114d.png)

**Comment by hannahkates** [comment]
We designed to app to only show the actions if there is more than one disposition action. In cases where there is only one action on the project, we are assuming they know what that action is (since it's the entire project) and don't need to see it listed.

The actions are displaying properly when there are multiple actions.
![image](https://user-images.githubusercontent.com/13967925/70280948-aab16e00-1787-11ea-9c61-e04fb4a95c29.png)

**Comment by ksinghprod** [comment]
Hi Hannah, the action name is still not displaying for a single public hearing 


![image](https://user-images.githubusercontent.com/57362229/70336025-733dd280-1816-11ea-8555-bada0c3d866f.png)

**Comment by hannahkates** [comment]
It's not supposed to when there's a single disposition. We designed the app to only show the action name if there is more than one disposition.

**Comment by ksinghprod** [comment]
Thanks for the clarification @hannahkates but then how does the LUP know for which action he/she is submitting a recommendation?

**Comment by gopal2020** [comment]
This Bug is closed as per Alien discussion.
