### ISSUE TITLE
On the Borough President Recommendation record, The Action information is not displaying

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#934]
Browser: Chrome
Actual Result: On the Borough President Recommendation record, The Action information is not displaying
Expected Result: The Action information should display On the Borough President Recommendation record. 

![image](https://user-images.githubusercontent.com/57265341/68893413-13f71180-06f3-11ea-880a-3c58f8067e97.png)

**Comment by gopal2020** [comment]
Missing actions has been observed in ZAP search as well. (one will appear but not all)

**Comment by gopal2020** [comment]
Related to #933

**Comment by trbmcginnis** [comment]
Closing and combining into #976

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

**Comment by ksinghprod** [comment]
This issue is now fixed

![image](https://user-images.githubusercontent.com/57362229/69575401-26e1cf80-0f98-11ea-93b4-dc4582da2790.png)

**Comment by ksinghprod** [comment]
Hi @hannahkates, 

This issue is back, the action name for hearings/recommendations is not being shown 

![image](https://user-images.githubusercontent.com/57362229/77927440-3a1de800-7275-11ea-9398-81690fd2a8bb.png)

**Comment by ksinghprod** [comment]
This issue is now fixed  
![image](https://user-images.githubusercontent.com/57362229/77952588-e8d41f80-7299-11ea-8c77-9783178a0a0f.png)
