### ISSUE TITLE
Stage: Same Project/Disposition displaying multiple time.

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#965]

**Comment by gopal2020** [comment]
Project Name: Happy Halloween

Actual Result: Project name displaying multiple time on LUP Portal
Expected Result: Project name should displaying single time on LUP Portal.

![image](https://user-images.githubusercontent.com/57265341/69182317-bd1c7e00-0ade-11ea-9a0a-0c284f651aaf.png)

**Comment by hannahkates** [comment]
This seems to occur when an LUP user is assigned to one project with the same role multiple times in CRM. I'm working on a SQL fix for the API that deduplicates the response when that happens.

**Comment by gopal2020** [comment]
It is Fixed. Now displaying only one disposition.
![image](https://user-images.githubusercontent.com/57265341/69758400-6ee62b00-112d-11ea-99fb-493e9b521b9c.png)

**Comment by ksinghprod** [comment]
This issue is back 

![image](https://user-images.githubusercontent.com/57362229/69982592-d3750180-1502-11ea-9719-67ce3a931867.png)

**Comment by andycochran** [comment]
If this is because an LUP user is assigned to one project with the same role multiple times in CRM, then this is simply a data issue, not a bug.

**Comment by ksinghprod** [comment]
@andycochran @hannahkates 

![image](https://user-images.githubusercontent.com/57362229/69991660-1be9ea80-1516-11ea-8ed5-cf31e3b7d152.png)

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

**Comment by ksinghprod** [comment]
This issue is not fixed, the view full project timeline option is not there 

![image](https://user-images.githubusercontent.com/57362229/70069099-35933c80-15bf-11ea-9d3b-f8c152c84f6b.png)

**Comment by ksinghprod** [comment]
This issue is fixed, it may come after a deployment or patch
