### ISSUE TITLE
Stage: User not  able to submit Recommendation Information

### ISSUE THREAD

**Issue by gopal2020** [NYCPlanning/labs-zap-search#973]
Project name: 2513-2523 Avenue O Rezoning

Expected Result: User should submit able to submit Recommendation Information

Actual Result: User Not able to submit Recommendation Information

![image](https://user-images.githubusercontent.com/57265341/69350403-7b5b1700-0c47-11ea-8c93-a97b9497b941.png)

**Comment by andycochran** [comment]
It looks like there was a regression in our recommendation form. It no longer includes vote counts and location. These are required by CRM and not providing them will cause the error.

**Comment by andycochran** [comment]
This could also be happening because a recommendation was already submitted in CRM?

**Comment by allthesignals** [comment]
submitted as BP. Not a regression. error message from crm is something about statecode and statuscode. These are probably misaligned.

**Comment by allthesignals** [comment]
```
statecode: 1
statuscode: 2
```

CRM is unhappy with this combo bc they don't validate together

**Comment by allthesignals** [comment]
> "2 is not a valid status code for state code dcp_communityboarddispositionState.Active on dcp_communityboarddisposition with Id cb0f8340-970b-ea11-a99d-001dd830809a.

**Comment by allthesignals** [comment]
```
{
  "data": {
    "id": "cb0f8340-970b-ea11-a99d-001dd830809a",
    "attributes": {
      "fullname": "",
      "dcp-publichearinglocation": "canal",
      "dcp-ispublichearingrequired": null,
      "dcp-dateofpublichearing": "2019-11-22T00:02:00.000Z",
      "dcp-boroughpresidentrecommendation": 717170000,
      "dcp-boroughboardrecommendation": null,
      "dcp-communityboardrecommendation": null,
      "dcp-consideration": "0\n",
      "dcp-votelocation": "",
      "dcp-datereceived": null,
      "dcp-dateofvote": null,
      "statuscode": 2,
      "statecode": 1,
      "dcp-docketdescription": null,
      "dcp-votinginfavorrecommendation": null,
      "dcp-votingagainstrecommendation": null,
      "dcp-votingabstainingonrecommendation": null,
      "dcp-totalmembersappointedtotheboard": null,
      "dcp-wasaquorumpresent": true
    },
    "relationships": {
      "project": {
        "data": {
          "type": "projects",
          "id": "P2017K0431"
        }
      },
      "assignment": {
        "data": {
          "type": "assignments",
          "id": "15ac2042-970b-ea11-a9aa-001dd8308025"
        }
      }
    },
    "type": "dispositions"
  }
}
```

**Comment by allthesignals** [comment]
@gopal2020 I can't move forward on this until I can verify what exactly is validated in terms of combinations of values for status and state codes.

**Comment by godfreyyeung** [comment]
Good catch @allthesignals , thanks.

I had indeed already pressed submit twice for this recommendation, like @andycochran mentioned. Just guessing: maybe in this case the state code was modified to reflect an already-submitted disposition?

(The first time the file upload failed for one POST. The second time all POSTs succeeded, but the UI froze and I'm not sure  if the recommendation values were successfully PATCHed. )

**Comment by allthesignals** [comment]
@godfreyyeung wanna make sure we're talking about the same issue :) this is a different rec issue with the api. the upload issue has already been solved.

**Comment by allthesignals** [comment]
I'm not sure why but this seems to have something to do with the previous state of the whole record, and the committed state of the record. I'm able to promote the record to the inactive submitted state:  statecode 1, statuscode 2 in a single transaction _after_ changing it to some other valid combination.

**Comment by allthesignals** [comment]
I can't reproduce this anymore....

**Comment by gopal2020** [comment]
If you able to submit , could you please attached screenshot.

Thanks
Gopal

**Comment by allthesignals** [comment]
I have a hunch that there's something about the dcp_visibility state that is affecting this... a mysterious dispo that was rejecting the 1/2 combo didn't seem to be pulling up in the API. Until I updated it's DCP_Visibility status...

**Comment by allthesignals** [comment]
We need to see how these dispositions were created in the first place. When I look up the records for these in the CRM GUI, I'm seeing this:

![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/8962eb1b-832f-41a7-b67b-6d225eec0d4a)
![Screen Shot 2019-11-21 at 2.32.58 PM.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/e68831a6-f096-402b-ac02-79bc4cf00bd7)

They don't have associated projects or naming.

**Comment by allthesignals** [comment]
I learned you can patch non-existent entity records by making up a valid guid:

![image.png](https://images.zenhubusercontent.com/5ca23922d9fcf5278d715977/9a94cd2c-7cbb-4f09-ae4b-46d5c6419296)

**Comment by allthesignals** [comment]
I'm putting this aside. @gopal2020 please try to assign new projects to yourself and keep attempting the recommendation.

This is probably a symptom of multiple testers/product owners using the same system and wires being crossed between that system and the ETL. Perhaps the project received non-existent disposition IDs.

**Comment by hannahkates** [comment]
This bug is resolved. QA Team please review.

**Comment by gopal2020** [comment]
@hannahkates @andycochran 

this issue is still not fixed

![image](https://user-images.githubusercontent.com/57265341/69993373-af70ea80-1519-11ea-890d-249d76e171de.png)

**Comment by allthesignals** [comment]
@gopal2020 might need a little more info: which project assignment is this? participant role?

**Comment by ksinghprod** [comment]
Matt here:

Error responses:

> A validation error occurred.  The value of 'dcp_votingagainstrecommendation' on record of type 'dcp_communityboarddisposition' is outside the valid range."

Data:
```
{"data":{"id":"2eaa871c-3015-ea11-a9bb-001dd8308fb0","attributes":{"fullname":"Komalpreet singh","dcp-publichearinglocation":"abccccccc","dcp-ispublichearingrequired":null,"dcp-representing":"Community Board","dcp-dateofpublichearing":"2019-12-19T06:13:00.000Z","dcp-nameofpersoncompletingthisform":"ZAP LUP Portal","dcp-projectaction":"b90fc6a8-fcf0-e911-a99e-001dd8308076","dcp-boroughpresidentrecommendation":null,"dcp-boroughboardrecommendation":null,"dcp-communityboardrecommendation":717170006,"dcp-consideration":"46464664","dcp-votelocation":"","dcp-datereceived":"2019-12-03T16:54:05.154Z","dcp-dateofvote":null,"statuscode":2,"statecode":1,"dcp-docketdescription":null,"dcp-votinginfavorrecommendation":45646464,"dcp-votingagainstrecommendation":646,"dcp-votingabstainingonrecommendation":646,"dcp-totalmembersappointedtotheboard":2,"dcp-wasaquorumpresent":false},"relationships":{"project":{"data":{"type":"projects","id":"2020K0251"}},"assignment":{"data":{"type":"assignments","id":"CB-01bcdc7d-fcf0-e911-a99e-001dd8308076"}}},"type":"dispositions"}}
```

This is because the other fields aren't validated. They need to be between 0-99

**Comment by hannahkates** [comment]
I think this is fixed now. QA team please recheck.

**Comment by ksinghprod** [comment]
This issue is still now fixed 
![image](https://user-images.githubusercontent.com/57362229/70088305-fc20f800-15e3-11ea-8959-f203b3f2c128.png)
